# Generated by Django 2.1.3 on 2018-11-19 02:49

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='iconmason.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('file', models.ImageField(default='', max_length=200, storage=django.core.files.storage.FileSystemStorage(location='../frontend/dist/static/media'), upload_to='svg')),
            ],
        ),
        migrations.CreateModel(
            name='IconSet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iconsets', to='iconmason.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='iconmason.IconSet'),
        ),
        migrations.AddField(
            model_name='icon',
            name='tags',
            field=models.ManyToManyField(related_name='icons', related_query_name='icon', to='iconmason.Tag'),
        ),
    ]
