# Generated by Django 2.1.3 on 2018-12-05 10:36

from django.db import migrations, models
import iconmason.models.icon


class Migration(migrations.Migration):

    dependencies = [
        ('iconmason', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='file',
            field=models.ImageField(default='', max_length=200, upload_to=iconmason.models.icon.upload_path),
        ),
    ]
