# Generated by Django 2.1.3 on 2018-12-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconmason', '0002_auto_20181205_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
